apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: s2i-dotnet1-taskrun
spec:
  # Use service account with git and image repo credentials
  #serviceAccount: test-build-robot 
  taskRef:
    name: s2i-dotnet1
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/utherp0/meowworldforum
  outputs:
    resources:
    - name: image
      resourceRef:
        name: meowworld-image
